FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential libgl1 libglib2.0-0 git wget

RUN pip install --upgrade pip
RUN pip install paddlepaddle==2.6.0
RUN pip install setuptools==75.8.0

COPY ./tools /app/tools
COPY ./ppocr /app/ppocr
COPY ./configs /app/configs
COPY ./document_app /app/document_app
COPY ./requirements.txt /app/requirements.txt

RUN mkdir /models && cd /models && \
    wget https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_distill_train.tar && \
    tar xf en_PP-OCRv3_det_distill_train.tar && rm -rf en_PP-OCRv3_det_distill_train.tar

RUN pip install -r /app/requirements.txt

WORKDIR /app