FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential libgl1 libglib2.0-0 git wget

RUN pip install --upgrade pip
RUN pip install paddlepaddle==2.6.0
RUN pip install setuptools==75.8.0
RUN pip install paddlehub==2.4.0

COPY ./tools /app/tools
COPY ./ppocr /app/ppocr
COPY ./configs /app/configs
COPY ./document_app /app/document_app
COPY ./requirements.txt /app/requirements.txt
COPY ./models/document_{document_id}_model_infer ./models/document_{document_id}_model_infer

RUN pip install -r /app/requirements.txt

WORKDIR /app